name: cosolvkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9,<3.12
  - openmmforcefields==0.12
  - pdbfixer 
  - mdanalysis 
  - espaloma 
  - pymol-open-source 
  - griddataformats
  - sphinx < 8.0
  - sphinx_rtd_theme >= 2.0 
   